### ISSUE TITLE
Android, can't run after installed library

### ISSUE THREAD

**Issue by lozyloop12** [Emurgo/react-native-haskell-shelley#61]
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/16531198/165473109-dc5faf48-8b5a-46f7-ab4c-13481271df52.png">

**Comment by lozyloop12** [comment]
Please guide me, is there anything else I need to do to be able to use this library

**Comment by stackchain** [comment]
Hey @lozyloop12, this is not an issue with the library, but with your environment, by the screenshot you've provided it looks like you are missing the java "stuff".

**Comment by lozyloop12** [comment]
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/16531198/165667646-137da8ae-6afe-4f64-b095-50cc2388c70e.png">
Hi @stackchain, Can you help me to fix this error: "Task with name 'cargoBuild' not found in project ':emurgo_react-native-haskell-shelley'."

**Comment by chidambararajab** [comment]
I am also facing the **same issue**, can someone help me with this?
