### ISSUE TITLE
[Android] Accessing blockchain from Android iOS code

### ISSUE THREAD

**Issue by lozyloop12** [Emurgo/react-native-haskell-shelley#62]
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/16531198/165898745-73b280ca-d25c-491f-8243-c4bd8684a78d.png">
I am having trouble getting the react-native-haskell-shelley to build as I run up against the following error when building.

“Task with name ‘cargoBuild’ not found in project ‘:@emurgo_react-native-haskell-shelley’”
Which seems to be from the android build.gradle line

**Comment by nntruong96** [comment]
I have the same issuse, i can't run android when install react-native-haskell-shelley.  You fixed it? 
can you help me, my gmail nhuttruong6496@gmail.com.

**Comment by stackchain** [comment]
considered answered, please re-open if you still need further assistance.
