### ISSUE TITLE
The version 9.1.4 of cardano-serialization-lib have issue with .gitmodule file

### ISSUE THREAD

**Issue by nntruong96** [Emurgo/react-native-haskell-shelley#70]
version 9.1.4
[submodule "binaryen"]
	path = binaryen
        url = git@github.com:WebAssembly/binaryen.git

New version
[submodule "binaryen"]
	path = binaryen
	url = https://github.com/WebAssembly/binaryen.git

The 9.1.4 version don't fetch the submodule binaryen

**Comment by stackchain** [comment]
hey @nntruong96, we will be creating a tag for this branch`chore/csl-9.1.5-rc.1`
