### ISSUE TITLE
Missing support for coin selection compare to other serialization libs 

### ISSUE THREAD

**Issue by khoanguyen-yang** [Emurgo/react-native-haskell-shelley#75]
I am looking for the method `TransactionBuilder.add_inputs_from` of `@emurgo/cardano-serialization-lib-nodejs` but can not find it in `@emurgo/react-native-haskell-shelley` (3.1.3)

The bindings for React Native seems do not provide any method for coin selection?

Many thanks! 🙏

**Comment by stackchain** [comment]
done
