### ISSUE TITLE
Install Error react-native-haskell-shelley on react native

### ISSUE THREAD

**Issue by Thinhnguyen185** [Emurgo/react-native-haskell-shelley#76]
Dear team, I'm using your lib to integrate with Cardano chain. In process setup, I have error relate cc on my Mac (m1 pro, Mac OS Monterey 12.6) and xCode 14.0.1
 
<img width="390" alt="Screen Shot 2022-10-06 at 13 57 05" src="https://user-images.githubusercontent.com/97153290/194234935-281332ea-3b06-4a1d-80a8-9b46272bd88d.png">

`react-native: 0.67.4
"@emurgo/react-native-haskell-shelley": "3.1.4",
`

**Comment by stackchain** [comment]
hey @Thinhnguyen185, you need an intel chip to compile it, we haven't optimized it for apple chips.

**Comment by dynamicstrategies** [comment]
Related to this:
https://github.com/Emurgo/react-native-haskell-shelley/issues/81

To workaround this error on a Mac  in the meantime you need
1- to make sure you add the right "rustup target ..."
2 - and you to amend the "build.sh" file as in this commit:
https://github.com/Emurgo/yoroi-mobile/pull/2260/commits/07a99a4f10d8f0d281b60f28bce33edf7e82ef6f
