### ISSUE TITLE
Add support for version of cardano-serialization-lib that supports Babbage era

### ISSUE THREAD

**Issue by jstolarek** [Emurgo/react-native-haskell-shelley#77]
What the title says: would it be possible to update the bindings so that they support latest versions of cardano-serialization-lib, and thus Babbage era new features (reference inputs, etc.)? This is a serious blocker in one of our projects. More generally, is react-native-haskell-shelley still being actively developed?

**Comment by vsubhuman** [comment]
Hi, @jstolarek , the library is actively developed, but only as a dependency to our Yoroi Mobile, which at the moment does not require Babbage features to be supported. We do have plans to have it updated to support these things, but it is not a priority at the moment. We could gladly accept a contribution in case someone wants to submit a change that adds this support. But from our side this change will not happen in the **nearest** future.

**Comment by jstolarek** [comment]
Just a quick question, since this is being closed as "completed". Is this really completed and will be available on the master branch Real Soon Now, or is this being closed because it's not being worked on?

**Comment by lisicky** [comment]
Hi @jstolarek . We are working on adding almost all functions from latest CSL, you can track it on this PR https://github.com/Emurgo/react-native-haskell-shelley/pull/84
