### ISSUE TITLE
Verifying signature is missing

### ISSUE THREAD

**Issue by bhoudebert** [Emurgo/react-native-haskell-shelley#83]
Hi there,

So first things first, great works, so far we base our work on this repo to be able to use the cardano lib through a flutter app (so using the iOS/C wrapper).

But unfortunately even if we can generate signature it seems that the `verify` function from the `cardano-serialization-lib` is missing.

We saw some comment on the Android (nothing in the iOS one) version saying that it was a pending thing waiting for something, but it seems it may not be the case anymore? https://github.com/Emurgo/react-native-haskell-shelley/blob/master/rust/src/android/public_key.rs
```C
// TODO: cannot implement yet since Ed25519Signature is missing.
// #[allow(non_snake_case)]
// #[no_mangle]
// pub unsafe extern "C" fn Java_io_emurgo_rnhaskellshelley_Native_publicKeyVerify(
```

Is there any reason to not have this function available, like a technical impossibility that we did not catch?

Thanks.

**Comment by lisicky** [comment]
Hi @bhoudebert . We are working on adding almost all functions from latest CSL, you can track it on this PR https://github.com/Emurgo/react-native-haskell-shelley/pull/84

**Comment by stackchain** [comment]
done
